### PR TITLE
Fixed using wine-ge-lol and added support for automated vsyscall32

### PR DESCRIPTION
**Pull request by polkaulfield**
The wine system install was used instead of wine-ge-lol, also added automation to the vsyscall command if you have already set it passwordless like here on step 3 https://www.reddit.com/r/leagueoflinux/comments/peylbm/fully_automate_abivsyscall32/

### CODE REVIEW

**Comment by polkaulfield** [comment]
Yeah I'll do it when i have some time. We have to get this game less tricky to install tbh.

**Comment by polkaulfield** [comment]
Added passwordless setup, tell me if it works fine!

**Comment by Ltrinch** [comment]
On the whole, it works, but there are a couple of problems. 
I had no `sudoers.d` folder and got an [error](https://imgur.com/a/Q0pS7LM) that the folder didn't exist. 
After creating the folder a [second problem](https://imgur.com/a/4LxLedw) with no permissions appeared, the problem is solved by removing `vsyscall32_passwordless` in `/tmp`. 
And after that everything works perfectly. Thank you.

**Comment by polkaulfield** [comment]
Oh i'll fix it, on Arch sudoers.d comes by default, at least on my installation. If you want to do a pull request on my fork I'll add it :)

**Comment by Ltrinch** [comment]
A new patch has been released where the abi.vsyscall32=0 requirement has been fixed, finally! #55

**Comment by kyechou** [comment]
Merged and fixed for the new wine-lol.

**Pull request closed without merging**
